# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: c89cb2e
_src_path: gh:scipp/copier_template
description: Scientific tiff format for imaging experiments.
max_python: '3.13'
min_python: '3.11'
namespace_package: ''
nightly_deps: scipp
orgname: scipp
prettyname: SciTiff
projectname: scitiff
related_projects: Scipp,Plopp,ESSImaging,EasyImaging
year: 2025
