name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string
      linkcheck:
        description: 'Run the link checker. If not set the link checker will not be run.'
        default: false
        required: false
        type: boolean

env:
  VERSION: ${{ inputs.version }}

jobs:
  docs:
    name: Build documentation
    runs-on: 'ubuntu-24.04'
    steps:
      - run: sudo apt install --yes graphviz pandoc
      - uses: actions/checkout@v6.0.3
        with:
          ref: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}
          fetch-tags: true  # history required to determine version
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: 0.70.1
          environment: docs
      - name: Install release version if needed
        if: ${{ inputs.version != '' }}
        run: |
          pixi add --pypi scitiff==${{ inputs.version }}
          pixi install -e docs
      - name: Build documentation
        run: pixi run docs
      - name: Linkcheck
        run: pixi run docs linkcheck
      - uses: actions/upload-artifact@v7.0.1
        id: artifact-upload-step
        with:
          name: docs_html
          path: html/
      - name: Generate docs preview link
        run: echo "::notice::https://remote-unzip.deno.dev/${{ github.repository }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}"
      - uses: JamesIves/github-pages-deploy-action@v4.8.0
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: html
          single-commit: true
