name: Nightly test at latest releases

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1-5'

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-24.04']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.1
          environments: default
          locked: false  # Ensure the lock file will be updated.
          frozen: false  # Ensure updated dependencies will be installed.
      - name: Run unit tests
        run: pixi run test
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: pixi-latest-release-lock-file
          path: pixi.lock
