name: Test

on:
  workflow_dispatch:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
      pixi-environment:  # default(3.11), py312, py313, py314
        default: 'default'
        type: string
      coverage-report:
        default: false
        type: boolean
      checkout_ref:
        default: ''
        type: string
  workflow_call:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
      pixi-environment:  # default(3.11), py312, py313, py314
        default: 'default'
        type: string
      coverage-report:
        default: false
        type: boolean
      checkout_ref:
        default: ''
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os-variant }}
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          ref: ${{ inputs.checkout_ref }}
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.1
          environments: ${{ inputs.pixi-environment }}
      - name: Run unit tests
        run: pixi run -e ${{ inputs.pixi-environment}} test
      - uses: actions/upload-artifact@v7.0.1
        if: ${{ inputs.coverage-report }}
        with:
          name: CoverageReport
          path: coverage_html/
